DOCTOR_SEED_DATA = [
    {
        "name": "Dr. Sarah Johnson",
        "speciality": "Cardiologist",
        "details": "Board-certified cardiologist focused on heart disease prevention and cardiac care.",
        "symptoms": "chest pain, shortness of breath, heart palpitations",
        "experience": 15,
        "location": "123 Heart Center, Medical District",
    },
    {
        "name": "Dr. Michael Chen",
        "speciality": "Pediatrician",
        "details": "Pediatric physician providing preventive care and treatment for children and adolescents.",
        "symptoms": "fever, cough, childhood allergies",
        "experience": 12,
        "location": "45 Children's Health Avenue",
    },
    {
        "name": "Dr. Aisha Patel",
        "speciality": "Dermatologist",
        "details": "Specializes in medical dermatology, skin health, and treatment of chronic skin conditions.",
        "symptoms": "rash, acne, eczema, itchy skin",
        "experience": 10,
        "location": "210 Riverside Medical Plaza",
    },
    {
        "name": "Dr. James Wilson",
        "speciality": "Neurologist",
        "details": "Neurologist experienced in evaluating headaches and disorders of the nervous system.",
        "symptoms": "migraine, headache, dizziness, numbness",
        "experience": 18,
        "location": "8 North Medical Tower",
    },
    {
        "name": "Dr. Maria Garcia",
        "speciality": "Family Medicine",
        "details": "Family physician offering primary care and ongoing wellness support for all ages.",
        "symptoms": "cold, flu, fatigue, sore throat",
        "experience": 14,
        "location": "76 Oak Street Clinic",
    },
    {
        "name": "Dr. David Kim",
        "speciality": "Orthopedic Surgeon",
        "details": "Orthopedic specialist treating joint, bone, and sports-related injuries.",
        "symptoms": "joint pain, back pain, sprains, knee pain",
        "experience": 16,
        "location": "500 Summit Orthopedics Center",
    },
    {
        "name": "Dr. Emily Brown",
        "speciality": "Endocrinologist",
        "details": "Provides care for hormone disorders, thyroid conditions, and diabetes management.",
        "symptoms": "excessive thirst, weight changes, thyroid symptoms",
        "experience": 11,
        "location": "19 Wellness Boulevard",
    },
    {
        "name": "Dr. Robert Davis",
        "speciality": "Pulmonologist",
        "details": "Pulmonary medicine specialist treating respiratory and lung conditions.",
        "symptoms": "shortness of breath, wheezing, persistent cough",
        "experience": 20,
        "location": "320 Lakeside Hospital Road",
    },
    {
        "name": "Dr. Priya Shah",
        "speciality": "Ophthalmologist",
        "details": "Eye physician providing comprehensive medical care for vision and eye conditions.",
        "symptoms": "blurred vision, eye pain, dry eyes",
        "experience": 9,
        "location": "62 Vision Care Lane",
    },
    {
        "name": "Dr. Daniel Thompson",
        "speciality": "Gastroenterologist",
        "details": "Specialist in digestive health and conditions affecting the gastrointestinal tract.",
        "symptoms": "abdominal pain, heartburn, nausea, bloating",
        "experience": 13,
        "location": "140 Central Medical Center",
    },
    {
        "name": "Dr. Olivia Martinez",
        "speciality": "Obstetrician-Gynecologist",
        "details": "Provides women's health care, preventive screenings, and pregnancy care.",
        "symptoms": "pelvic pain, menstrual cramps, pregnancy concerns",
        "experience": 17,
        "location": "25 Women's Health Way",
    },
    {
        "name": "Dr. William Anderson",
        "speciality": "Psychiatrist",
        "details": "Psychiatrist offering assessment and treatment for common mental health conditions.",
        "symptoms": "anxiety, depression, insomnia, panic attacks",
        "experience": 19,
        "location": "11 Cedar Grove Medical Suites",
    },
    {
        "name": "Dr. Sophia Lee",
        "speciality": "Otolaryngologist",
        "details": "ENT specialist treating ear, nose, and throat conditions in adults and children.",
        "symptoms": "earache, sinus congestion, sore throat, hearing loss",
        "experience": 8,
        "location": "90 Midtown Specialty Clinic",
    },
    {
        "name": "Dr. Ethan Robinson",
        "speciality": "Rheumatologist",
        "details": "Treats inflammatory and autoimmune conditions affecting joints and connective tissue.",
        "symptoms": "joint stiffness, swollen joints, muscle pain",
        "experience": 14,
        "location": "410 Greenway Medical Plaza",
    },
    {
        "name": "Dr. Grace Nguyen",
        "speciality": "Urologist",
        "details": "Urologist providing evaluation and treatment for urinary tract and bladder conditions.",
        "symptoms": "urinary urgency, bladder pain, kidney stones",
        "experience": 12,
        "location": "7 Harbor Health Center",
    },
    {
        "name": "Dr. Noah Taylor",
        "speciality": "Oncologist",
        "details": "Medical oncologist coordinating evidence-based cancer diagnosis and treatment.",
        "symptoms": "unexplained weight loss, persistent fatigue, cancer care",
        "experience": 21,
        "location": "300 Hope Cancer Institute",
    },
    {
        "name": "Dr. Isabella Clark",
        "speciality": "Allergist",
        "details": "Allergy and immunology physician helping patients manage allergic conditions.",
        "symptoms": "sneezing, hives, seasonal allergies, nasal congestion",
        "experience": 10,
        "location": "55 Spring Medical Offices",
    },
    {
        "name": "Dr. Lucas White",
        "speciality": "Emergency Medicine Physician",
        "details": "Emergency physician experienced in urgent assessment and stabilization of acute illness.",
        "symptoms": "acute pain, minor injuries, sudden fever",
        "experience": 15,
        "location": "1 City General Hospital",
    },
]
