/**
 * Render smoke test (generated by the pipeline — deterministic).
 *
 * Mounts the real App with the api client mocked to return rows and
 * asserts the UI actually renders something. Catches the blank-screen
 * class (render throws, bad shape access, hook error) that reading the
 * source cannot see.
 */
import { describe, it, expect, vi } from "vitest";
import { render, waitFor } from "@testing-library/react";
import React from "react";
import App from "./App";

vi.mock("./services/api", () => {
  // A permissive row: whichever field the UI reads, it gets a value.
  const SMOKE_ROWS = [
    {
      id: 1,
      name: "Smoke Row",
      title: "Smoke Row",
      label: "Smoke Row",
      description: "Smoke Row",
      url: "https://example.com/smoke",
      link: "https://example.com/smoke",
      snippet: "Smoke Row",
      status: "active",
    },
  ];
  return {
    searchDoctors: vi.fn(async () => SMOKE_ROWS),
    default: { get: vi.fn(async () => ({ data: SMOKE_ROWS })), post: vi.fn(async () => ({ data: SMOKE_ROWS })) },
  };
});

describe("App render smoke", () => {
  it("mounts and renders visible content", async () => {
    const { container } = render(<><App /></>);
    await waitFor(() => {
      expect(container.textContent.trim().length).toBeGreaterThan(0);
    });
  });
});
